parameters:
  buildConfig: 'Release'
  
steps:
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: ${{parameters.buildConfig}}
  displayName: 'building solution with msbuild'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)/PowerVolumeInterface/bin/${{parameters.buildConfig}}'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-nodrama-${{parameters.buildConfig}}.zip'
    replaceExistingArchive: true
